version: '3.8'

services:
  mqtt:
    image: 'emqx'
    restart: always
    ports:
      - '1883:1883'
      - '18083:18083'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass babajendujiji
  
volumes:
  redis_data: