version: '3.8'

services:
  web:
    build: ./web
    restart: always
    ports:
      - '5000:80'
    environment:
      - VITE_APP_BASE=cfeee1e5e4e00a.ru:8000
  backend:
    build: ./backend
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mqtt
      - redis
      - mongo
      - influx

  mqtt:
    image: 'emqx'
    restart: always
    ports:
      - '1883:1883'
      - '18083:18083'
    volumes:
      - mqtt_data:/opt/emqx/data
      - mqtt_log:/opt/emqx/log
      - mqtt_config:/opt/emqx/etc

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass babajendujiji

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfeee1e5e4e00a
    volumes:
      - mongo_data:/data/db

  influx:
    image: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=cfeee1e5e4e00a
      - DOCKER_INFLUXDB_INIT_ORG=cfeee1e5e4e00a
      - DOCKER_INFLUXDB_INIT_BUCKET=logs
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning/
    ports:
      - '3000:3000'
    depends_on:
      - influx

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_config:
  mongo_data:
  redis_data:
  influx_data:
  influx_config:
  grafana_data:
  grafana_provisioning:
